# Generated by Django 4.2 on 2026-05-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_category_remove_signup_ph_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
