# Generated by Django 4.2 on 2026-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_menuitem_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
