# Generated by Django 4.2 on 2026-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_signup_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
