# Generated by Django 4.2 on 2026-05-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_signup_city_signup_state_signup_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
