# Generated by Django 4.2 on 2026-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_signup_is_verified_signup_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='resend_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
