# Generated by Django 4.2 on 2026-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_signup_resend_count_alter_signup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
