# Generated by Django 4.2 on 2026-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_signup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='verify_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
