# Generated by Django 4.2 on 2026-05-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_signup_verify_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='resend_count',
        ),
    ]
