# Generated by Django 4.2 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_signup_resend_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('starters', 'Starters'), ('main_course', 'Main Course'), ('grills', 'Grills'), ('pasta', 'Pasta'), ('soups', 'Soups'), ('drinks', 'Drinks'), ('desserts', 'Desserts')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('prep_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, help_text='Comma-separated list of ingredients', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('orders_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'menu_item',
                'ordering': ['-date_added'],
            },
        ),
    ]
