# Generated by Django 4.2 on 2026-05-22 07:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='passport',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[320, 300], upload_to='passport/'),
        ),
    ]
