# Generated by Django 4.2 on 2026-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_menuitem_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='passport',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
