# Generated by Django 4.2 on 2026-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice'), ('swallow', 'Swallow'), ('soups', 'Soups'), ('small_chops', 'Small Chops'), ('grills', 'Grills'), ('drinks', 'Drinks'), ('dessert', 'Dessert'), ('others', 'Others')], max_length=50),
        ),
    ]
