# Generated by Django 4.2 on 2026-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_order_payment_reference_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('customers', 'Customers Only'), ('vendors', 'Vendors Only'), ('riders', 'Riders Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='signup',
            name='payments',
        ),
    ]
