# Generated by Django 4.2 on 2026-08-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
