# Generated by Django 4.2 on 2026-09-30 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _backfill_visibility(apps, schema_editor):
    Notification = apps.get_model('food', 'Notification')
    # Manual broadcasts were user-facing -> public.
    # System/order rows were internal -> keep admin-private.
    Notification.objects.filter(notification_type='manual').update(visibility='public')
    Notification.objects.exclude(notification_type='manual').update(visibility='admin')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0023_address_lga'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='visibility',
            field=models.CharField(choices=[('admin', 'Admin only (private)'), ('public', 'Public broadcast'), ('private', 'Private (one user)')], default='admin', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='food.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_read',
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.RunPython(_backfill_visibility, migrations.RunPython.noop),
    ]
